### PR TITLE
<script> and {%script} processing changes

### PR DESCRIPTION
**Pull request by romanrudenko**
Changes:
minify {%script}{/script} contents only in production mode (that is, when client is invoked with -m or builds a bundle to production).
Remove leading <!-- and <![CDATA for the purpose of minification. This ensures that copy/pasted scripts with those HTML comments will be minified properly.
Make script pragma minification forgiving. If minification fails, emit original code and code snippet that emits error to browser console.
Recognize <script></script> and disable normal Dust whitespace suppression inside.

### CODE REVIEW

**Comment by ericmuyser** [comment]
Cool to close this @jansepar ?

**Comment by jansepar** [comment]
Haha, oh man, this is still open? Yes I think it's safe to close :) Thanks for going through all of this old PRs btw!!

**Comment by rrjamie** [comment]
Please unsubscribe me from this mailinglist.

**Comment by tedtate** [comment]
Get me off this wild ride!

**Comment by jansepar** [comment]
[Weeeeeeeeeeeee](https://www.youtube.com/watch?v=SozkRxUdbSg)

**Pull request closed without merging**
